### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by LNERDSIM** [macedonga/lofi.twitch.auto.stream#2]
Hi! Get this error? Can you fix it?

TypeError: Cannot read properties of undefined (reading 'match')
    at createSizeFilters (/app/node_modules/fluent-ffmpeg/lib/options/videosize.js:79:29)
    at FfmpegCommand.proto.withSize.proto.setSize.proto.size (/app/node_modules/fluent-ffmpeg/lib/options/videosize.js:209:19)
    at Object.module.exports.Start (/app/stream.js:45:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by macedonga** [comment]
Have you set the enviroment variables as told on the readme?

**Comment by LNERDSIM** [comment]
Yes: 
Have set an .env file. Can you fix it?

**Comment by macedonga** [comment]
What did you set the `VIDEO_SIZE` variable to?

**Comment by LNERDSIM** [comment]
1920x1080

**Comment by LNERDSIM** [comment]
Btw  (Using heroku)
